package GUI;

import Claves.ClaveString;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YERSY
 */
public class TablaNuevaPestania extends javax.swing.JFrame {

    DefaultTableModel modelo;
    boolean _editable;
    GUI gui;

    ClaveString clave;

    /**
     *
     * @param clave
     * @param editable
     * @param gui
     */
    public TablaNuevaPestania(ClaveString clave, boolean editable, GUI gui) {
        this._editable = editable;
        this.clave = clave;
        this.gui = gui;

        initComponents();
        cargarInformacionDeGUI();
        look();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTabla = new javax.swing.JTable();
        jlblNombreClaveMatriz = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnmNuevo = new javax.swing.JButton();
        jrbtnModificable = new javax.swing.JRadioButton();
        jbtnmExportar = new javax.swing.JButton();
        jbtnmModificar = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtNullClave = new javax.swing.JTextField();
        jtxtNullMatriz = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblLengthNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz"));

        jtblTabla.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jtblTabla.setForeground(new java.awt.Color(51, 51, 60));
        jtblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "A1", "B1", "C1", "D1"},
                {"A2", "a", "b", "c", "d"},
                {"B2", "e", "f", "g", "h"},
                {"C2", "i", "j", "k", "l"},
                {"D2", "m", "n", "ñ", "o"}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblTabla.setColumnSelectionAllowed(true);
        jtblTabla.setGridColor(new java.awt.Color(153, 153, 153));
        jtblTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtblTabla);
        jtblTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jlblNombreClaveMatriz.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblNombreClaveMatriz.setForeground(new java.awt.Color(153, 153, 153));
        jlblNombreClaveMatriz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreClaveMatriz.setText("Convertir número decimal a hexadecimal");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbtnmNuevo.setText("Nuevo");
        jbtnmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmNuevoActionPerformed(evt);
            }
        });

        jrbtnModificable.setBackground(new java.awt.Color(255, 255, 255));
        jrbtnModificable.setText("Editable");
        jrbtnModificable.setEnabled(false);
        jrbtnModificable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnModificableActionPerformed(evt);
            }
        });

        jbtnmExportar.setText("Exportar");
        jbtnmExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmExportarActionPerformed(evt);
            }
        });

        jbtnmModificar.setText("Aplicar Cambios");
        jbtnmModificar.setEnabled(false);
        jbtnmModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmModificarActionPerformed(evt);
            }
        });

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Null Clave:");

        jLabel3.setText("Null Matríz:");

        jtxtNombre.setEditable(false);
        jtxtNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtxtNombre.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombre.setBorder(null);
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jtxtNullClave.setEditable(false);
        jtxtNullClave.setBackground(new java.awt.Color(255, 255, 255));
        jtxtNullClave.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNullClave.setBorder(null);

        jtxtNullMatriz.setEditable(false);
        jtxtNullMatriz.setBackground(new java.awt.Color(255, 255, 255));
        jtxtNullMatriz.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNullMatriz.setBorder(null);

        jlblLengthNombre.setBackground(new java.awt.Color(255, 255, 255));
        jlblLengthNombre.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jlblLengthNombre.setForeground(new java.awt.Color(102, 102, 102));
        jlblLengthNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblLengthNombre.setText("50");
        jlblLengthNombre.setToolTipText("");
        jlblLengthNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtNullMatriz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbtnModificable, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addComponent(jtxtNombre))
                        .addGap(18, 18, 18)
                        .addComponent(jlblLengthNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtNullClave, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jbtnmNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnmExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnmModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtNullClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxtNullMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblLengthNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnmNuevo)
                            .addComponent(jbtnmExportar)
                            .addComponent(jbtnmModificar)
                            .addComponent(jbtnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtnModificable)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblNombreClaveMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jlblNombreClaveMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmNuevoActionPerformed
        System.out.println(modelo.getValueAt(1, 1));
    }//GEN-LAST:event_jbtnmNuevoActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea resetear los datos?, perderá los cambios que haya realizado.") == 0) {
            modelo = clave.getTableModel(clave.isEditable());
            jtblTabla.setModel(modelo);
        }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnmModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmModificarActionPerformed
        if (_editable) {
            if (clave.modificar_Clave(modelo, jtxtNombre.getText(), jtxtNullClave.getText(), jtxtNullMatriz.getText(), jrbtnModificable.isSelected())) {
                //clave aceptada
                Mensajes m = new Mensajes();
                jlblNombreClaveMatriz.setText(jtxtNombre.getText());
                gui.guardarClaves();
                m.mostrarMensaje("La clave ha sido actualizada!", "/imagenes/icons8-Cita recurrente-25.png");
            }
        }
    }//GEN-LAST:event_jbtnmModificarActionPerformed

    private void jbtnmExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmExportarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Se exportará la clave con los últimos cambios guardados.") == 0) {
            ArrayList<ClaveString> k = new ArrayList<>();
            k.add(this.clave);
            String arch = k.get(0).getNombre() + ".cskey";
            String ruta = GUI.getRutaGuardar(new FileNameExtensionFilter("Archivos cskey", "cskey"), arch);
            if (!ruta.equals(arch)) {
                GUI.guardarObjeto(ruta, k, "Clave guardada!");
            }
        }
    }//GEN-LAST:event_jbtnmExportarActionPerformed

    private void jrbtnModificableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnModificableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnModificableActionPerformed

    private void jtxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyReleased
        ponerLengthNombre();
    }//GEN-LAST:event_jtxtNombreKeyReleased

    private void jtxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyPressed
        ponerLengthNombre();
    }//GEN-LAST:event_jtxtNombreKeyPressed

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        String i = jtxtNombre.getText();
        if(i.length()>49){
            evt.consume();
            GUI.mostrarMensaje("El máximo número de caractéres permitidos para el nombre es de 50.\nIngrese un nombre de máximo 50 caracteres.");
        }
    }//GEN-LAST:event_jtxtNombreKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnmExportar;
    private javax.swing.JButton jbtnmModificar;
    private javax.swing.JButton jbtnmNuevo;
    private javax.swing.JLabel jlblLengthNombre;
    private javax.swing.JLabel jlblNombreClaveMatriz;
    private javax.swing.JRadioButton jrbtnModificable;
    private javax.swing.JTable jtblTabla;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNullClave;
    private javax.swing.JTextField jtxtNullMatriz;
    // End of variables declaration//GEN-END:variables

    private void look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaNuevaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaNuevaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaNuevaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaNuevaPestania.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * carga la información a presentar, utiliza una clave
     */
    private void cargarInformacionDeGUI() {
        jlblNombreClaveMatriz.setText(clave.getNombre());//llenar el nombre de la matriz
        jrbtnModificable.setSelected(clave.isEditable());
        jrbtnModificable.setEnabled(_editable ? clave.isEditable() : false);
        modelo = clave.getTableModel(_editable ? clave.isEditable() : false);
        jtblTabla.setModel(modelo);

        jtxtNombre.setEditable(_editable ? clave.isEditable() : false);
        jtxtNullClave.setEditable(_editable ? clave.isEditable() : false);
        jtxtNullMatriz.setEditable(_editable ? clave.isEditable() : false);
        jbtnmModificar.setEnabled((_editable ? clave.isEditable() : false));

        jtxtNombre.setText(clave.getNombre());
        jtxtNullClave.setText(clave.getNullClave());
        jtxtNullMatriz.setText(clave.getNullMatriz());
        
        jlblLengthNombre.setText(jtxtNombre.getText().length()+"");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/hexa-50.png"));

        return retValue;
    }

    private void ponerLengthNombre() {
        jlblLengthNombre.setText(jtxtNombre.getText().length()+"");
    }
}
